### ISSUE TITLE
Reg : Real world implementation

### ISSUE THREAD

**Issue by johnd2010** [VIS4ROB-lab/fast_multi_robot_exploration#1]
Hi, 

Thank you for sharing your research. We were planning to implement your algorithm in our drones. 
Can you please let us know of the easiest method for integration. 
Would it be possible to extend it to 3D Lidars such as velodyne?

Thanks and Regards,
John D

**Comment by lucaBartolomei** [comment]
Hi @johnd2010,
Thanks for the interest in the project. I would suggest to follow the same procedure that was followed for [RACER](https://github.com/SYSU-STAR/RACER). I would suggest to check their original paper.

In theory our algo can be adapted to use point clouds from velodyne / LiDARs.
I will close this issue because it is not directly related to a problem with the code, but feel free to reopen.
