### ISSUE TITLE
The digital 3D model of  a real forest. 

### ISSUE THREAD

**Issue by YuQ-Zhou** [VIS4ROB-lab/fast_multi_robot_exploration#2]
Hello,

Thank you for sharing this amazing open source project. 

I did not find the 3D model of the real forest in the code. Can you provide the 3D model of the real forest reconstruction used in the releate paper? Or can you tell me where I can get this model?

Thank you in advance for your help.

Best regards.

**Comment by lucaBartolomei** [comment]
Hi @YuQ-Zhou ,

Thanks for the interest in our project, and sorry for the late reply.

Unfortunately, we are unable to share those models, as they are proprietary models that were shared with us from a third party.
I would suggest searching in the [Unity Asset Store](https://assetstore.unity.com/search#q=tree) for tree models (if you use Unity), or [Sketchfab](https://sketchfab.com/search?features=downloadable&q=tree&type=models) (recommended, because some models are free). There you can find a large variety of tree models you could use.

I hope this helps.
